name: ${pluginName}
version: ${version}
main: com.willfp.ecoskills.EcoSkillsPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
depend:
  - eco
softdepend:
  - libreforge

commands:
  ecoskills:
    description: Base Command
    permission: ecoskills.command.ecoskills
  skills:
    aliases:
      - skill
    description: Open the skills menu
    permission: ecoskills.command.skills
  stats:
    aliases:
      - stat
    description: Open the stats menu
    permission: ecoskills.command.stats

permissions:
  ecoskills.*:
    description: All ecoskills permissions
    default: op
    children:
      ecoskills.command.*: true
  ecoskills.command.*:
    description: All commands
    default: op
    children:
      ecoskills.command.reload: true
      ecoskills.command.ecoskills: true
      ecoskills.command.reset: true
      ecoskills.command.skills: true
      ecoskills.command.stats: true
      ecoskills.command.give: true
      ecoskills.command.set: true
      ecoskills.command.top: true
      ecoskills.command.recount: true
      ecoskills.command.toggleactionbar: true
      ecoskills.command.togglexpgainsound: true

  ecoskills.command.reload:
    description: Allows reloading the config
    default: op
  ecoskills.command.ecoskills:
    description: Allows the use of /ecoskills.
    default: true
  ecoskills.command.skills:
    description: Allows the use of /skills.
    default: true
  ecoskills.command.stats:
    description: Allows the use of /stats.
    default: true
  ecoskills.command.reset:
    description: Allows the use of /ecoskills reset.
    default: op
  ecoskills.command.top:
    description: Allows the use of /ecoskills top.
    default: true
  ecoskills.command.give:
    description: Allows the use of /ecoskills give.
    default: op
  ecoskills.command.set:
    description: Allows the use of /ecoskills set.
    default: op
  ecoskills.command.recount:
    description: Allows the use of /ecoskills recount.
    default: op
  ecoskills.command.toggleactionbar:
    description: Allows the use of /skills toggleactionbar.
    default: op
  ecoskills.command.togglexpgainsound:
    description: Allows the use of /skills togglexpgainsound.
    default: op

  ecoskills.xpmultiplier.50percent:
    description: Gives the player 50% more skill experience
    default: false
  ecoskills.xpmultiplier.double:
    description: Gives the player 2x skill experience
    default: false
  ecoskills.xpmultiplier.triple:
    description: Gives the player 3x skill experience
    default: false
  ecoskills.xpmultiplier.quadruple:
    description: Gives the player 4x skill experience
    default: false